FROM alpine:3.20

LABEL maintainer="nakat-t <armaiti.wizard@gmail.com>" \
      description="Docker image for Doxygen and PlantUML documentation generator."

# Set environment variables for versions
ENV DOXYGEN_VERSION=1.11.0-r0
ENV GRAPHVIZ_VERSION=9.0.0-r2

# PlantUML version and installation directory
ENV PLANTUML_VERSION=1.2024.6-r0
ENV PLANTUML_INSTALL_DIR=/opt/plantuml

RUN apk update && \
    apk add --no-cache openjdk11-jdk

# Install OpenJDK 19 (JDK), Doxygen, Graphviz, Fontconfig, and PlantUML dependencies
# IMPORTANT: OpenJDK 19 might be in the 'community' repository.
# We need to uncomment it in /etc/apk/repositories if it's not already enabled.
RUN apk update && \
    apk add --no-cache apk add doxygen=${DOXYGEN_VERSION} \
    graphviz=${GRAPHVIZ_VERSION} \
    fontconfig \
    font-noto \
    font-noto-emoji \
    font-noto-cjk \
    curl

# Install PlantUML
RUN mkdir -p ${PLANTUML_INSTALL_DIR} && \
    curl -L "https://sourceforge.net/projects/plantuml/files/plantuml.${PLANTUML_VERSION}.jar/download" -o ${PLANTUML_INSTALL_DIR}/plantuml.jar && \
    test -f ${PLANTUML_INSTALL_DIR}/plantuml.jar && \
    apk del curl && \
    rm -rf /var/cache/apk/*

# Verify installations (optional, but good for debugging)
#RUN java -version
RUN doxygen --version
RUN dot -V
#RUN java -jar ${PLANTUML_INSTALL_DIR}/plantuml.jar -version

# Set the working directory
WORKDIR /data

# Set the PLANTUML_JAR_PATH environment variable for Doxygen
ENV PLANTUML_JAR_PATH=${PLANTUML_INSTALL_DIR}/plantuml.jar

ENTRYPOINT [""]